function is_right = is_right_rotation(locations)
%IS_RIGHT_ROTATION Check if QR code on the right rotation.
%   locations: squares of QR code location.
    min_x = min(locations(:, 2));
    min_y = min(locations(:, 3));

    is_right = (check_between(locations(1, 3), min_y-2, min_y+2) ...
        && check_between(locations(2, 3), min_y-2, min_y+2) ...
        && check_between(locations(3, 2), min_x-2, min_x+2)) || ...
        (check_between(locations(3, 3), min_y-2, min_y+2) ...
        && check_between(locations(1, 3), min_y-2, min_y+2) ...
        && check_between(locations(2, 2), min_x-2, min_x+2)) || ...
        (check_between(locations(2, 3), min_y-2, min_y+2) ...
        && check_between(locations(3, 3), min_y-2, min_y+2) ...
        && check_between(locations(1, 2), min_x-2, min_x+2));
end

